# Generated by Django 5.2.4 on 2025-12-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('caracteristicas', models.JSONField(blank=True, default=list)),
                ('fotos', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
