# Generated by Django 5.2.4 on 2025-12-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='app1.categoria'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='app1.tecnologia'),
        ),
    ]
